import Link from "next/link";

export default function MethodologyPage() {
  return (
    <div className="min-h-screen pt-32 pb-20 px-8 max-w-[1440px] mx-auto">
      <div className="max-w-3xl mx-auto">
        <Link
          href="/"
          className="text-[#B8B2A4] hover:text-[#C8A96A] transition-colors duration-500 text-xs tracking-[0.12em] uppercase font-light"
        >
          ← Back to Home
        </Link>

        <div className="gold-line my-10" />

        <h1 className="font-light text-4xl md:text-5xl text-[#F5F2EA] mb-4 tracking-[-0.02em]">
          Methodology &amp; Pipeline
        </h1>
        <p className="text-[#B8B2A4] text-sm font-light mb-10 tracking-wide">
          How artworks are selected, verified, enriched, and displayed
        </p>

        <section className="space-y-8 text-[#E6E6E6] text-sm font-light leading-relaxed tracking-wide">
          <div className="p-6 rounded-[12px] bg-[#161616] border border-[#232323]">
            <h2 className="text-[#C8A96A] text-xs tracking-[0.12em] uppercase mb-3 font-light">
              1. Curation — Curator Agent
            </h2>
            <p>
              Artworks are sourced from museum open-access APIs and Wikimedia Commons. The Curator
              Agent selects works based on public domain status, image quality, and metadata
              completeness. Supported data sources include museum API endpoints and structured
              open-access datasets.
            </p>
          </div>

          <div className="p-6 rounded-[12px] bg-[#161616] border border-[#232323]">
            <h2 className="text-[#C8A96A] text-xs tracking-[0.12em] uppercase mb-3 font-light">
              2. Compliance — Compliance Agent
            </h2>
            <p>
              Each artwork is checked for public domain eligibility. The Compliance Agent verifies
              that the work is not under active copyright based on known public domain rules,
              museum licensing metadata, and Wikimedia categorization. Works that fail compliance
              checks are excluded.
            </p>
            <p className="mt-3 text-[#555] text-xs">
              Note: Compliance checks are automated and may contain errors. Independent verification
              is recommended before any commercial reuse.
            </p>
          </div>

          <div className="p-6 rounded-[12px] bg-[#161616] border border-[#232323]">
            <h2 className="text-[#C8A96A] text-xs tracking-[0.12em] uppercase mb-3 font-light">
              3. Enrichment — Content Agent
            </h2>
            <p>
              The Content Agent generates enriched metadata including descriptions, audio narration
              scripts, tags, and movement classifications. These are generated using AI models and
              may contain inaccuracies. Original museum-provided metadata is preserved where available.
            </p>
          </div>

          <div className="p-6 rounded-[12px] bg-[#161616] border border-[#232323]">
            <h2 className="text-[#C8A96A] text-xs tracking-[0.12em] uppercase mb-3 font-light">
              4. Categorization — Categorizer Agent
            </h2>
            <p>
              Artworks are categorized by art movement, period, medium, and geographic origin. These
              categorizations are generated by AI and may not reflect current art-historical consensus.
              Movements are assigned based on artist association, creation period, and stylistic analysis.
            </p>
          </div>

          <div className="p-6 rounded-[12px] bg-[#161616] border border-[#232323]">
            <h2 className="text-[#C8A96A] text-xs tracking-[0.12em] uppercase mb-3 font-light">
              5. Design &amp; Layout — Designer Agent
            </h2>
            <p>
              The Designer Agent generates the 3D gallery layout, assigning artworks to rooms,
              calculating wall positions, and creating the spatial arrangement. Rooms are organized
              by movement or theme, and artwork positions are computed for optimal viewing.
            </p>
          </div>

          <div className="p-6 rounded-[12px] bg-[#161616] border border-[#232323]">
            <h2 className="text-[#C8A96A] text-xs tracking-[0.12em] uppercase mb-3 font-light">
              Data Storage
            </h2>
            <p>
              Artwork metadata is stored in a Supabase (PostgreSQL) database and as a local JSON file.
              Images are served remotely from Wikimedia Commons and partner museum CDNs. No user data,
              analytics, or personal information is collected or stored by this prototype.
            </p>
          </div>

          <div className="p-6 rounded-[12px] bg-[#161616] border border-[#232323]">
            <h2 className="text-[#C8A96A] text-xs tracking-[0.12em] uppercase mb-3 font-light">
              Limitations
            </h2>
            <ul className="list-disc list-inside space-y-2 text-[#E6E6E6]">
              <li>Artwork coverage depends on museum API availability and rate limits</li>
              <li>AI-generated descriptions may contain hallucinations or inaccuracies</li>
              <li>Public domain status is automatically determined and not legally binding</li>
              <li>Image URLs may break if upstream sources change or deprecate endpoints</li>
              <li>The 3D environment requires WebGL support and may not work on all devices</li>
            </ul>
          </div>
        </section>

        <div className="gold-line my-10" />

        <p className="text-[#555] text-xs font-light text-center">
          This methodology document is itself a living draft and will be updated as the pipeline evolves.
        </p>
      </div>
    </div>
  );
}
