import logging
from typing import Any

logger = logging.getLogger("CuratorAgent")

MASTERPIECES: list[dict[str, Any]] = [
    {
        "id": "mona-lisa",
        "title": "Mona Lisa (La Gioconda)",
        "artist": "Leonardo da Vinci",
        "year": 1503,
        "movement": "Renaissance",
        "origin": "Italy",
        "medium": "Oil on poplar panel",
        "museum": "Louvre, Paris",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
        "dimensions": "77 cm x 53 cm",
    },
    {
        "id": "starry-night",
        "title": "The Starry Night",
        "artist": "Vincent van Gogh",
        "year": 1889,
        "movement": "Post-Impressionism",
        "origin": "France",
        "medium": "Oil on canvas",
        "museum": "MoMA, New York",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
        "dimensions": "73.7 cm x 92.1 cm",
    },
    {
        "id": "girl-pearl-earring",
        "title": "Girl with a Pearl Earring",
        "artist": "Johannes Vermeer",
        "year": 1665,
        "movement": "Baroque",
        "origin": "Netherlands",
        "medium": "Oil on canvas",
        "museum": "Mauritshuis, The Hague",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Vermeer%2C_Johannes_-_Girl_with_a_Pearl_Earring.jpg/800px-Vermeer%2C_Johannes_-_Girl_with_a_Pearl_Earring.jpg",
        "dimensions": "44.5 cm x 39 cm",
    },
    {
        "id": "great-wave",
        "title": "The Great Wave off Kanagawa",
        "artist": "Katsushika Hokusai",
        "year": 1831,
        "movement": "Ukiyo-e",
        "origin": "Japan",
        "medium": "Woodblock print",
        "museum": "Met Museum, New York",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tsunami_by_hokusai_19th_century.jpg/1280px-Tsunami_by_hokusai_19th_century.jpg",
        "dimensions": "25.7 cm x 37.8 cm",
    },
    {
        "id": "night-watch",
        "title": "The Night Watch",
        "artist": "Rembrandt van Rijn",
        "year": 1642,
        "movement": "Baroque",
        "origin": "Netherlands",
        "medium": "Oil on canvas",
        "museum": "Rijksmuseum, Amsterdam",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_HD.jpg/1280px-The_Night_Watch_-_HD.jpg",
        "dimensions": "363 cm x 437 cm",
    },
    {
        "id": "birth-venus",
        "title": "The Birth of Venus",
        "artist": "Sandro Botticelli",
        "year": 1485,
        "movement": "Renaissance",
        "origin": "Italy",
        "medium": "Tempera on canvas",
        "museum": "Uffizi Gallery, Florence",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project.jpg/1280px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project.jpg",
        "dimensions": "172.5 cm x 278.9 cm",
    },
    {
        "id": "liberty-leading",
        "title": "Liberty Leading the People",
        "artist": "Eugene Delacroix",
        "year": 1830,
        "movement": "Romanticism",
        "origin": "France",
        "medium": "Oil on canvas",
        "museum": "Louvre, Paris",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg/1280px-Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg",
        "dimensions": "260 cm x 325 cm",
    },
    {
        "id": "wanderer-fog",
        "title": "Wanderer above the Sea of Fog",
        "artist": "Caspar David Friedrich",
        "year": 1818,
        "movement": "Romanticism",
        "origin": "Germany",
        "medium": "Oil on canvas",
        "museum": "Kunsthalle Hamburg",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/800px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg",
        "dimensions": "94.8 cm x 74.8 cm",
    },
    {
        "id": "american-gothic",
        "title": "American Gothic",
        "artist": "Grant Wood",
        "year": 1930,
        "movement": "Regionalism",
        "origin": "United States",
        "medium": "Oil on beaverboard",
        "museum": "Art Institute of Chicago",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/American_Gothic.jpg/800px-American_Gothic.jpg",
        "dimensions": "78 cm x 65.3 cm",
    },
    {
        "id": "sunday-la-grande-jatte",
        "title": "A Sunday on La Grande Jatte",
        "artist": "Georges Seurat",
        "year": 1886,
        "movement": "Post-Impressionism",
        "origin": "France",
        "medium": "Oil on canvas",
        "museum": "Art Institute of Chicago",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884%2C_Oil_on_canvas.jpg/1280px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884%2C_Oil_on_canvas.jpg",
        "dimensions": "207.6 cm x 308 cm",
    },
    {
        "id": "nighthawks",
        "title": "Nighthawks",
        "artist": "Edward Hopper",
        "year": 1942,
        "movement": "American Realism",
        "origin": "United States",
        "medium": "Oil on canvas",
        "museum": "Art Institute of Chicago",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Nighthawks_%281942%29_by_Edward_Hopper.jpg/1280px-Nighthawks_%281942%29_by_Edward_Hopper.jpg",
        "dimensions": "84.1 cm x 152.4 cm",
    },
    {
        "id": "kiss-klimt",
        "title": "The Kiss",
        "artist": "Gustav Klimt",
        "year": 1908,
        "movement": "Art Nouveau",
        "origin": "Austria",
        "medium": "Oil and gold leaf on canvas",
        "museum": "Belvedere, Vienna",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/800px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
        "dimensions": "180 cm x 180 cm",
    },
    {
        "id": "persistence-memory",
        "title": "The Persistence of Memory",
        "artist": "Salvador Dali",
        "year": 1931,
        "movement": "Surrealism",
        "origin": "Spain",
        "medium": "Oil on canvas",
        "museum": "MoMA, New York",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/The_Persistence_of_Memory.jpg/800px-The_Persistence_of_Memory.jpg",
        "dimensions": "24.1 cm x 33 cm",
    },
    {
        "id": "milkmaid",
        "title": "The Milkmaid",
        "artist": "Johannes Vermeer",
        "year": 1660,
        "movement": "Baroque",
        "origin": "Netherlands",
        "medium": "Oil on canvas",
        "museum": "Rijksmuseum, Amsterdam",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/The_milkmaid_%28Het_melkmeisje%29_-_Johannes_Vermeer_-_Google_Art_Project.jpg/800px-The_milkmaid_%28Het_melkmeisje%29_-_Johannes_Vermeer_-_Google_Art_Project.jpg",
        "dimensions": "45.5 cm x 41 cm",
    },
    {
        "id": "sistine-chapel",
        "title": "The Creation of Adam (Sistine Chapel ceiling)",
        "artist": "Michelangelo",
        "year": 1512,
        "movement": "Renaissance",
        "origin": "Italy",
        "medium": "Fresco",
        "museum": "Sistine Chapel, Vatican",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/1280px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg",
        "dimensions": "280 cm x 570 cm",
    },
    {
        "id": "water-lilies",
        "title": "Water Lilies",
        "artist": "Claude Monet",
        "year": 1906,
        "movement": "Impressionism",
        "origin": "France",
        "medium": "Oil on canvas",
        "museum": "Art Institute of Chicago",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_%281906%29.JPG/800px-Claude_Monet_-_Water_Lilies_%281906%29.JPG",
        "dimensions": "89.9 cm x 94.1 cm",
    },
    {
        "id": "scream",
        "title": "The Scream",
        "artist": "Edvard Munch",
        "year": 1893,
        "movement": "Expressionism",
        "origin": "Norway",
        "medium": "Tempera and crayon on cardboard",
        "museum": "National Gallery, Oslo",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/800px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg",
        "dimensions": "91 cm x 73.5 cm",
    },
    {
        "id": "luncheon-boating",
        "title": "Luncheon of the Boating Party",
        "artist": "Pierre-Auguste Renoir",
        "year": 1881,
        "movement": "Impressionism",
        "origin": "France",
        "medium": "Oil on canvas",
        "museum": "Phillips Collection, Washington D.C.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Luncheon_of_the_Boating_Party_by_Pierre-Auguste_Renoir.jpg/1280px-Luncheon_of_the_Boating_Party_by_Pierre-Auguste_Renoir.jpg",
        "dimensions": "129.9 cm x 172.7 cm",
    },
]


class CuratorAgent:
    async def select_artworks(self) -> list[dict]:
        logger.info(f"Curating from knowledge base of {len(MASTERPIECES)} masterpieces")
        return MASTERPIECES.copy()
